/*
 * Proyecto educativo
 * Universidad Autonoma del Estado de Hidalgo
 * Sistema Experto Diagnostico Electrico Automotriz
 */
package Ventanas;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/***
 * @Lider Yadhira Villeda Trejo
 * @Analista Ivan Felipe Campos Esparza
 * @Programador Jose Luis Alvarez Roldan
 */

public class Inicial extends javax.swing.JFrame {

    /**
     * Creates new form Inicial
     */
    public Inicial() {
        initComponents();
        ImageIcon imagen1= new ImageIcon(getClass().getResource("/imagenes/descarga.jpeg"));
        Icon fondo1=new ImageIcon(imagen1.getImage().getScaledInstance(lblimagen1.getWidth(), lblimagen1.getHeight(), Image.SCALE_DEFAULT));
        lblimagen1.setIcon(fondo1);
        ImageIcon imagen2= new ImageIcon(getClass().getResource("/imagenes/uaeh_logo_color.png"));
        Icon fondo2=new ImageIcon(imagen2.getImage().getScaledInstance(lblimagen2.getWidth(), lblimagen2.getHeight(), Image.SCALE_DEFAULT));
        lblimagen2.setIcon(fondo2);
        ImageIcon imagen3= new ImageIcon(getClass().getResource("/imagenes/Fondo.jpg"));
        Icon fondoa=new ImageIcon(imagen3.getImage().getScaledInstance(Fondo.getWidth(), Fondo.getHeight(), Image.SCALE_DEFAULT));
        Fondo.setIcon(fondoa);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblimagen1 = new javax.swing.JLabel();
        lblimagen2 = new javax.swing.JLabel();
        BtnUser = new javax.swing.JButton();
        BtnDocente = new javax.swing.JButton();
        BtnInfo = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(lblimagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 17, 154, 129));
        getContentPane().add(lblimagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 17, 251, 155));

        BtnUser.setText("Usuarios");
        BtnUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUserActionPerformed(evt);
            }
        });
        getContentPane().add(BtnUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 223, -1, -1));

        BtnDocente.setText("Docente");
        BtnDocente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDocenteActionPerformed(evt);
            }
        });
        getContentPane().add(BtnDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 223, -1, -1));

        BtnInfo.setText("Información");
        BtnInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInfoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 223, -1, -1));
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 530, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnUserActionPerformed

    private void BtnDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDocenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnDocenteActionPerformed

    private void BtnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDocente;
    private javax.swing.JButton BtnInfo;
    private javax.swing.JButton BtnUser;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel lblimagen1;
    private javax.swing.JLabel lblimagen2;
    // End of variables declaration//GEN-END:variables
}
